# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'BAViperModules' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

    pod 'Typhoon'
    pod 'ViperMcFlurry'
    pod 'RamblerTyphoonUtils/AssemblyCollector'
    pod 'AFNetworking'
    pod 'ReactiveCocoa', '2.5'

  # Pods for BAViperModules

end
